# Generated by Django 2.2.16 on 2022-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yauser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='yauser',
            name='first_name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='yauser',
            name='last_name',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
